on:
  workflow_dispatch:
  
name: deploy Non-prod
jobs:
  deploy:
    environment: NonProd
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_NONPROD }}
        tenant-id: ${{ secrets.AZURE_TENANT_NONPROD }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_NONPROD }}
      # Deploy ARM template  
    - name: deploy_NonProd_vm
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_NONPROD }}
        resourceGroupName: ${{ secrets.AZURE_RG_NONPROD }}
        template: ./AzurePlex/vm.json
